# generated by datamodel-codegen:
#   filename:  bgpvrfs_schema.yaml
#   timestamp: 2025-11-12T10:03:49+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field

from .shared import DeletionPolicy, Dependency, LifecyclePolicy, Status


class Config(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    as_number: Annotated[str, Field(alias='asNumber')]
    ipv4_address: Annotated[str, Field(alias='ipv4Address')]
    maximum_path_ebgp: Annotated[int, Field(alias='maximumPathEBGP')]
    maximum_path_ibgp: Annotated[int, Field(alias='maximumPathIBGP')]
    rd: int
    vrf_name: Annotated[str | None, Field(alias='vrfName')] = None


class Spec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    config: Annotated[
        Config,
        Field(
            description='BGPVRFConfig defines the configuration for BGP VRF settings.'
        ),
    ]
    deletion_policy: Annotated[
        DeletionPolicy | None,
        Field(
            alias='deletionPolicy',
            description='DeletionPolicy controls the behavior when the Kubernetes resource is deleted.\nDelete means both the Kubernetes and external resources are deleted.\nOrphan means only the Kubernetes resource is deleted, leaving the external resource.',
        ),
    ] = DeletionPolicy.delete
    dependencies: Annotated[
        list[Dependency] | None,
        Field(
            description='Dependencies lists resources that must exist and be Ready before this resource can be created or updated.'
        ),
    ] = None
    device_address: Annotated[
        str,
        Field(
            alias='deviceAddress',
            description='DeviceAddress is the IP:Port of the device.\n"IP" is the management IP and "Port" is the gNMI TCP port configured for the device.',
            pattern=r'^(?:[0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]{1,5}$',
        ),
    ]
    lifecycle_policies: Annotated[
        list[LifecyclePolicy] | None,
        Field(
            alias='lifecyclePolicies',
            description='LifecyclePolicies controls which operations Crossnet performs on the external resource.\nThe default is that all operations are performed.',
        ),
    ] = [LifecyclePolicy.create, LifecyclePolicy.update, LifecyclePolicy.delete]
    paused: Annotated[
        bool | None,
        Field(
            description='Paused indicates whether Crossnet should operate on the resource or not.'
        ),
    ] = None


class BGPVRF(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    api_version: Annotated[
        str | None,
        Field(
            alias='apiVersion',
            description='APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources',
        ),
    ] = None
    kind: Annotated[
        str | None,
        Field(
            description='Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
        ),
    ] = None
    metadata: dict[str, Any] | None = None
    spec: Annotated[
        Spec | None,
        Field(description='BGPVRFSpec defines the desired state of BGPVRF.'),
    ] = None
    status: Annotated[
        Status | None,
        Field(description='BGPVRFStatus defines the observed state of BGPVRF.'),
    ] = None
