# generated by datamodel-codegen:
#   filename:  vrfs_schema.yaml
#   timestamp: 2025-11-12T10:03:46+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field

from .shared import DeletionPolicy, Dependency, LifecyclePolicy, Status


class RouteTarget(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int
    name: int
    stitching: bool


class Export(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    route_policy_name: Annotated[str | None, Field(alias='routePolicyName')] = None
    route_targets: Annotated[list[RouteTarget] | None, Field(alias='routeTargets')] = (
        None
    )
    to_allow_imported_vpn: Annotated[bool, Field(alias='toAllowImportedVPN')]


class Import(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    from_vrf_advertise_as_vpn: Annotated[bool, Field(alias='fromVRFAdvertiseAsVPN')]
    route_policy_name: Annotated[str | None, Field(alias='routePolicyName')] = None
    route_targets: Annotated[list[RouteTarget] | None, Field(alias='routeTargets')] = (
        None
    )


class Ipv4(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    export: Annotated[
        Export | None, Field(description='Export defines VRF export configuration.')
    ] = None
    import_: Annotated[
        Import | None,
        Field(alias='import', description='Import defines VRF import configuration.'),
    ] = None


Export1 = Export


Import1 = Import


class Ipv6(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    export: Annotated[
        Export1 | None, Field(description='Export defines VRF export configuration.')
    ] = None
    import_: Annotated[
        Import1 | None,
        Field(alias='import', description='Import defines VRF import configuration.'),
    ] = None


class Config(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str
    ipv4: Annotated[
        Ipv4 | None,
        Field(
            description='IPUnicast contains IPv4 or IPv6 unicast address family configuration.'
        ),
    ] = None
    ipv6: Annotated[
        Ipv6 | None,
        Field(
            description='IPUnicast contains IPv4 or IPv6 unicast address family configuration.'
        ),
    ] = None
    name: str


class Spec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    config: Annotated[
        Config, Field(description='VRFConfig defines the configuration for a VRF.')
    ]
    deletion_policy: Annotated[
        DeletionPolicy | None,
        Field(
            alias='deletionPolicy',
            description='DeletionPolicy controls the behavior when the Kubernetes resource is deleted.',
        ),
    ] = DeletionPolicy.delete
    dependencies: Annotated[
        list[Dependency] | None,
        Field(
            description='Dependencies lists resources that must exist and be Ready before this resource can be created or updated.'
        ),
    ] = None
    device_address: Annotated[
        str,
        Field(
            alias='deviceAddress',
            description='DeviceAddress is the IP:Port of the device.',
            pattern=r'^(?:[0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]{1,5}$',
        ),
    ]
    lifecycle_policies: Annotated[
        list[LifecyclePolicy] | None,
        Field(
            alias='lifecyclePolicies',
            description='LifecyclePolicies controls which operations Crossnet performs on the external resource.',
        ),
    ] = [LifecyclePolicy.create, LifecyclePolicy.update, LifecyclePolicy.delete]
    paused: Annotated[
        bool | None,
        Field(
            description='Paused indicates whether Crossnet should operate on the resource or not.'
        ),
    ] = None


class VRF(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    api_version: Annotated[
        str | None,
        Field(
            alias='apiVersion',
            description='APIVersion defines the versioned schema of this representation of an object.',
        ),
    ] = None
    kind: Annotated[
        str | None,
        Field(
            description='Kind is a string value representing the REST resource this object represents.'
        ),
    ] = None
    metadata: dict[str, Any] | None = None
    spec: Annotated[
        Spec | None, Field(description='VRFSpec defines the desired state of VRF.')
    ] = None
    status: Annotated[
        Status | None, Field(description='VRFStatus defines the observed state of VRF.')
    ] = None
